---
# Ansible playbook
# Home work #8 - Services WITHOUT Docker
# 
# VM Slave 1: group = build
#   - make artefact by https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
#   - send artefact to https://github.com/spring108/artifactory.git
# VM Slave 2: group = prod
#   - install apache tomcat
#   - get artefact from https://github.com/spring108/artifactory.git
#   - run service

- name: group "build" - prepare infrastructure
  hosts: build
  become: yes
  tasks:
  - name: Ensure GIT package is present
    apt:
      name: git
      state: present
  - name: Ensure JAVA package is present
    apt:
      name: default-jdk
      state: present
  - name: Ensure MAVEN package is present
    apt:
      name: maven
      state: present


- name: group "build" - make the artifact
  hosts: build
  become: yes
  tasks:
  - name: "Clone GIT Repository for PROJECT"
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse-sample-java-war-hello
      clone: yes
      update: yes
  - name: Clean the artifact
    file:
      path: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      state: absent
  - name: Build the artifact
    shell: cd /tmp/boxfuse-sample-java-war-hello && mvn package
  - name: Check the artifact exists
    file:
      path: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      state: file
  - name: Check the artifact exists 2
    stat:
      path: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war


- name: group "build" - upload artifact into ARTIFACTORY
  hosts: build
  become: yes
  vars:
    git_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63633166316436376133373362663866343737643635303861303661663262633330393366646235
          3061343736316362643763313436616637376138366335310a623035663663363134313764633032
          32353234633066656666653833316435323139386330376466316234616534613566356462343935
          6161613435346631390a306163336532396464383736326632653939633932653962393062356239
          38386539316336643631646266353934623733633837313461353237643735353439343336326530
          3530383439656438316435343836623035663732616363623561

  tasks:
  - name: Delete repository folder for ARTIFACTORY
    file:
      path: /tmp/artifactory
      state: absent
  - name: "Clone a github repository for ARTIFACTORY"
    git:
      repo: https://github.com/spring108/artifactory.git
      dest: /tmp/artifactory
      clone: yes
      update: yes
  - name: Copy the artifact to git dir
    copy:
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/artifactory/hello.war
      force: true
      remote_src: yes
  - name: GIT Push to ARTIFACTORY-1-1
    #shell: git config --global user.name "Igor Skripnikov" &&  git config --global user.email "garik108@narod.ru"
    git:
      name: user.name
      repo: /tmp/artifactory
      scope: global
      value: Igor Skripnikov
  - name: GIT Push to ARTIFACTORY-1-2
    #shell: git config --global user.name "Igor Skripnikov" &&  git config --global user.email "garik108@narod.ru"
    git:
      name: user.email
      repo: /tmp/artifactory
      scope: global
      value: garik108@narod.ru
  - name: GIT Push to ARTIFACTORY-2
    shell: cd /tmp/artifactory && git add . && git commit -m "artifact changet"
  - name: GIT Push to ARTIFACTORY-3
    shell: cd /tmp/artifactory && git push https://spring108:{{ git_token }}@github.com/spring108/artifactory.git



- name: group "prod" - prepare infrastructure
  hosts: prod
  become: yes
  tasks:
  - name: group "prod" - Ensure TOMCAT package is present
    apt:
      name: tomcat9
      state: present
  - name: group "prod" - Ensure GIT package is present
    apt:
      name: git
      state: present
- name: group "prod" - RUN Service
  hosts: prod
  become: yes
  tasks:
  - name: group "prod" - Delete repository folder for ARTIFACTORY
    file:
      path: /tmp/artifactory
      state: absent
  - name: group "prod" - Clone a github repository for ARTIFACTORY
    git:
      repo: https://github.com/spring108/artifactory.git
      dest: /tmp/artifactory
      clone: yes
      update: yes
  - name: group "prod" - Copy the artifact to webapps folder
    copy:
      src: /tmp/artifactory/hello.war
      dest: /var/lib/tomcat9/webapps/hello.war
      force: true
      remote_src: yes

